services:
  database:
    container_name: mysql-database
    build:
      context: ./.docker/database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"

  apache:
    container_name: php-apache
    build:
      context: ./.docker/apache
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # - ./certs/mycert.crt:/etc/ssl/certs/mycert.crt
      # - ./certs/mycert.key:/etc/ssl/private/mycert.key
    ports:
      - "8080:80"
      # - "8443:443"

volumes:
  db-data:
