services:
  database:
    container_name: mysql-database
    build:
      context: ./.docker/database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"

  apache:
    container_name: php-apache
    build:
      context: ./.docker/apache
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
      - "443:443"

volumes:
  db-data:
